services:
  # Backend service running Poem OpenAPI.
  backend:
    build: ./backend/docker
    init: true
    volumes:
      - ./scripts:/opt/scripts:ro
      - ./backend:/opt/backend
      - ./openapi:/opt/openapi # dev.sh will write spec.json here.

      # Use anonymous volumes to cache data on container config change.
      - backend_cargo_target_dir:/opt/cargo_target_dir
      - backend_cargo_registry:/opt/cargo_home/registry

    working_dir: /opt/backend
    environment:
      - CARGO_TARGET_DIR=/opt/cargo_target_dir
    command: watchexec --restart -- ./dev.sh
    ports:
      - 3000:3000

  # Generate front reqwest client from spec.json.
  openapi:
    build: openapi/docker
    init: true
    volumes:
      - ./openapi:/opt/openapi
    working_dir: /opt/openapi
    command: ./dev.sh
    depends_on:
      - backend

volumes:
  backend_cargo_target_dir:
  backend_cargo_registry:
