services:
  traefik:
    build: .
    environment:
      - TZ=Europe/Paris
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /run/user/${UID}/docker.sock:/var/run/docker.sock:ro
      - ./dynamic-conf:/etc/traefik/dynamic-conf
      - /opt/docker-volumes/traefik/acme.json:/etc/traefik/acme.json
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.tangram-orchestre.fr`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=resolver
      - traefik.http.routers.dashboard.middlewares=authentik@file
