services:
  showcase-website-staging:
    image: ghcr.io/tangram-orchestre/showcase-website:staging
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - traefik.enable=true
      - "traefik.http.routers.staging-website.rule=Host(`www.staging.tangram-orchestre.fr`)"
      - traefik.http.routers.staging-website.tls=true
      - traefik.http.routers.staging-website.tls.certresolver=resolver
      - traefik.http.routers.staging-website.middlewares=authentik@file
