name: Detect Changes
description: Detect Changes to know what to build

inputs:
  ref_branch:
    description: Branch to compare against
outputs:
  need-rebuild:
    description: "Should Showcase Website be build"
    value: ${{ steps.changes.outputs.need-rebuild }}

runs:
  using: "composite"
  steps:
  - name: Detect Changes
    uses: dorny/paths-filter@v3
    id: changes
    with:
      base: ${{ inputs.ref_branch }}
      filters: |
        need-rebuild:
          - 'services/showcase-website/**'
          - 'services/backend/**'
          - '.github/workflows/build-showcase-website.yml'


