name: Build Containers
description: Build Containers

inputs:
  DOCKER_REGISTRY:
    description: Docker Registry, if absent, no push
  SHOWCASE_WEBSITE_IMAGE_NAME:
    description: Image name to push
  BACKEND_IMAGE_NAME:
    description: Image name to push
  TAG:
    description: Tag for docker image

runs:
  using: "composite"
  steps:
    # Only download images if we're deploying the image, they're not needed to
    # check the build is passing.
    - name: Download LFS images
      if: inputs.DOCKER_REGISTRY != ''
      shell: bash
      run: git lfs pull --include "showcase-website/**"


    - name: Docker meta Backend
      if: inputs.DOCKER_REGISTRY != ''
      id: meta-backend
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=raw,value=${{ inputs.TAG }}
          type=sha,format=long
        images: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.BACKEND_IMAGE_NAME }}

    - name: Build and push
      id: push-backend
      uses: docker/build-push-action@v6
      with:
        context: backend
        push: ${{ inputs.DOCKER_REGISTRY != '' }}
        tags: backend,${{ inputs.DOCKER_REGISTRY != '' && steps.meta-backend.outputs.tags }}
        labels: ${{ inputs.DOCKER_REGISTRY != '' && steps.meta-backend.outputs.labels || ''}}
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate OpenAPI spec
      shell: bash
      run: |
        docker run --rm \
          -v ./openapi:/opt/openapi \
          -e PUBLIC_OPENAPI_SPEC_PATH=/opt/openapi/spec.json \
          backend
        cp openapi/spec.json showcase-website/spec.json


    - name: Docker meta Showcase Website
      if: inputs.DOCKER_REGISTRY != ''
      id: meta-showcase-website
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=raw,value=${{ inputs.TAG }}
          type=sha,format=long
        images: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.SHOWCASE_WEBSITE_IMAGE_NAME }}

    - name: Build and push
      id: push-showcase-website
      uses: docker/build-push-action@v6
      with:
        context: showcase-website
        push: ${{ inputs.DOCKER_REGISTRY != '' }}
        tags: ${{ steps.meta-showcase-website.outputs.tags }}
        labels: ${{ steps.meta-showcase-website.outputs.labels }}
        # Build with cache is slower!
        # cache-from: type=gha
        # cache-to: type=gha,mode=max

    - name: Generate artifact attestation
      if: inputs.DOCKER_REGISTRY != ''
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.BACKEND_IMAGE_NAME }}
        subject-digest: ${{ steps.push-backend.outputs.digest }}
        push-to-registry: true

    - name: Generate artifact attestation
      if: inputs.DOCKER_REGISTRY != ''
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.SHOWCASE_WEBSITE_IMAGE_NAME }}
        subject-digest: ${{ steps.push-showcase-website.outputs.digest }}
        push-to-registry: true
