name: Build Containers
description: Build Containers

inputs:
  PUSH_TO_REGISTRY:
    description: Push to registry
    required: false
    default: "false"
  TAG:
    description: Tag for docker image

runs:
  using: "composite"
  steps:
    - name: Configure env
      shell:  bash
      run: |
        echo "BACKEND_IMAGE_NAME=${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/backend" >> $GITHUB_ENV
        echo "SHOWCASE_WEBSITE_IMAGE_NAME=${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/showcase-website" >> $GITHUB_ENV


    - name: Docker meta Backend
      id: meta-backend
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=raw,value=${{ inputs.TAG }}
          type=sha,format=long
        images: ${{ env.BACKEND_IMAGE_NAME }}

    - name: Build and push
      id: push-backend
      uses: docker/build-push-action@v6
      with:
        context: services/backend
        push: ${{ inputs.PUSH_TO_REGISTRY }}
        tags: ${{ steps.meta-backend.outputs.tags }}
        labels: ${{ steps.meta-backend.outputs.labels}}
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max


    - name: Generate OpenAPI spec
      shell: bash
      run: |
        cd services
        docker run --rm \
          -v ./openapi:/opt/openapi \
          -e PUBLIC_OPENAPI_SPEC_PATH=/opt/openapi/spec.json \
          ${{ env.BACKEND_IMAGE_NAME }}:sha-${{ github.sha }}
        cp openapi/spec.json showcase-website/spec.json

    # Only download images if we're deploying the image, they're not needed to
    # check the build is passing.
    - name: Download LFS images
      if: inputs.PUSH_TO_REGISTRY == 'true'
      shell: bash
      run: git lfs pull --include "services/showcase-website/**"

    - name: Docker meta Showcase Website
      id: meta-showcase-website
      uses: docker/metadata-action@v5
      with:
        tags: |
          type=raw,value=${{ inputs.TAG }}
          type=sha,format=long
        images: ${{ env.SHOWCASE_WEBSITE_IMAGE_NAME }}

    - name: Build and push
      id: push-showcase-website
      uses: docker/build-push-action@v6
      with:
        context: services/showcase-website
        push: ${{ inputs.PUSH_TO_REGISTRY }}
        tags: ${{ steps.meta-showcase-website.outputs.tags }}
        labels: ${{ steps.meta-showcase-website.outputs.labels }}
        # Build with cache is slower!
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
