services:
  portal-staging:
    image: ghcr.io/tangram-orchestre/portal:staging
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - dev.dozzle.name=Portal
      - dev.dozzle.group=Staging
      - traefik.enable=true
      - "traefik.http.routers.staging-portal.rule=Host(`portal.staging.tangram-orchestre.fr`)"
      # Lesser priority than backend-staging to avoid conflicts on /api prefix
      - traefik.http.routers.staging-portal.priority=1
      - traefik.http.routers.staging-portal.tls=true
      - traefik.http.routers.staging-portal.tls.certresolver=resolver
      - traefik.http.routers.staging-portal.middlewares=authentik@file
