include:
  - ./traefik/docker-compose.yaml
  - ./authentik/docker-compose.yaml
  - ./planka/docker-compose.yaml
  - ./watchtower/docker-compose.yaml
  - ./kopia/docker-compose.yaml
  - ./backend/docker-compose.yaml
  - ./website/docker-compose.yaml

services:
  unhealthy_container_restarter:
    image: docker:cli
    network_mode: none
    cap_drop:
      - ALL
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command:
      [
        "/bin/sh",
        "-c",
        "while true; do sleep 60; docker ps -q -f health=unhealthy | xargs --no-run-if-empty docker restart; done",
      ]
    restart: unless-stopped

networks:
  default:
    name: services
