providers:
  file:
    directory: /etc/traefik/dynamic-conf
    watch: true
  docker:
    exposedByDefault: false

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"

# log:
#   level: TRACE

# accesslog:
#   addInternals: true