include:
  - ./website/docker-compose.yaml
  - ./backend/docker-compose.yaml

services:
  maildev:
    image: maildev/maildev:2.2.1
    environment:
      - MAILDEV_MAIL_DIRECTORY=/opt/maildev
    user: root:root
    volumes:
      - /opt/docker-volumes-no-backup/maildev:/opt/maildev
    labels:
      - traefik.enable=true
      - traefik.http.routers.maildev.rule=Host(`maildev.tangram-orchestre.fr`)
      - traefik.http.routers.maildev.tls=true
      - traefik.http.routers.maildev.tls.certresolver=resolver
      - traefik.http.services.maildev.loadbalancer.server.port=1080

networks:
  default:
    name: services
    external: true
