include:
  - ./website/docker-compose.yaml
  - ./backend/docker-compose.yaml
  - ./portal/docker-compose.yaml

services:
  maildev:
    image: maildev/maildev:2.2.1
    restart: unless-stopped
    environment:
      - MAILDEV_MAIL_DIRECTORY=/opt/maildev
    user: root:root
    volumes:
      - /opt/docker-volumes-no-backup/maildev:/opt/maildev
    labels:
      - traefik.enable=true
      - traefik.http.routers.maildev.rule=Host(`maildev.tangram-orchestre.fr`)
      - traefik.http.routers.maildev.tls=true
      - traefik.http.routers.maildev.tls.certresolver=resolver
      - traefik.http.services.maildev.loadbalancer.server.port=1080
      - traefik.http.routers.maildev.middlewares=authentik@file

  whoami:
    image: traefik/whoami:v1.11
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.tangram-orchestre.fr`)
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=resolver
      - traefik.http.routers.whoami.middlewares=authentik@file

networks:
  default:
    name: services
    external: true
