// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  Composable,
  TDataShape,
  Client,
} from "@hey-api/client-nuxt";
import type {
  GetPublicAltchaChallengeData,
  PostPublicSendContactFormData,
  PostPublicSendContactFormError,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TComposable extends Composable,
  TData extends TDataShape = TDataShape,
  ResT = unknown,
  DefaultT = undefined,
> = ClientOptions<TComposable, TData, ResT, DefaultT> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getPublicAltchaChallenge = <
  TComposable extends Composable,
  DefaultT = undefined,
>(
  options: Options<
    TComposable,
    GetPublicAltchaChallengeData,
    unknown,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).get<
    TComposable,
    unknown | DefaultT,
    unknown,
    DefaultT
  >({
    url: "/public/altcha_challenge",
    ...options,
  });
};

export const postPublicSendContactForm = <
  TComposable extends Composable,
  DefaultT = undefined,
>(
  options: Options<
    TComposable,
    PostPublicSendContactFormData,
    unknown,
    DefaultT
  >,
) => {
  return (options.client ?? _heyApiClient).post<
    TComposable,
    unknown | DefaultT,
    PostPublicSendContactFormError,
    DefaultT
  >({
    url: "/public/send_contact_form",
    ...options,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      ...options?.headers,
    },
  });
};
