// This file is auto-generated by @hey-api/openapi-ts

export type GetTestData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/test";
};

export type GetTestResponses = {
  200: string;
};

export type GetTestResponse = GetTestResponses[keyof GetTestResponses];

export type ClientOptions = {
  baseURL: string;
};
