// This file is auto-generated by @hey-api/openapi-ts

export type ContactForm = {
  /**
   * Name of the sender
   */
  name: string;
  /**
   * Email name of the sender
   */
  email: string;
  /**
   * Subject of the message
   */
  subject: string;
  /**
   * Message to be sent
   */
  message: string;
  /**
   * Altcha captcha
   */
  altcha: unknown;
};

export type GetPublicAltchaChallengeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/public/altcha_challenge";
};

export type GetPublicAltchaChallengeResponses = {
  200: unknown;
};

export type PostPublicSendContactFormData = {
  body: ContactForm;
  path?: never;
  query?: never;
  url: "/public/send_contact_form";
};

export type PostPublicSendContactFormErrors = {
  400: string;
};

export type PostPublicSendContactFormError =
  PostPublicSendContactFormErrors[keyof PostPublicSendContactFormErrors];

export type PostPublicSendContactFormResponses = {
  200: unknown;
};

export type ClientOptions = {
  baseURL: string;
};
