services:
  showcase-website:
    image: ghcr.io/tangram-orchestre/showcase-website:production
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - NUXT_PRIVATE_API_BASE_URL=http://backend-staging:3000
      - NUXT_PUBLIC_API_BASE_URL=https://www.tangram-orchestre.fr/api
    labels:
      - traefik.enable=true
      - "traefik.http.routers.website.rule=Host(`tangram-orchestre.fr`) || Host(`www.tangram-orchestre.fr`)"
      - "traefik.http.middlewares.redirect-none-to-www.redirectregex.regex=^https://tangram-orchestre\\.fr(.*)$$"
      - "traefik.http.middlewares.redirect-none-to-www.redirectregex.replacement=https://www.tangram-orchestre.fr$${1}"
      - traefik.http.routers.website.middlewares=redirect-none-to-www@docker
      - traefik.http.routers.website.tls=true
      - traefik.http.routers.website.tls.certresolver=resolver
      - com.centurylinklabs.watchtower.enable=false
