services:
  # lgtm:
  #   image: grafana/otel-lgtm:0.8.6
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - /opt/docker-volumes-no-backup/lgtm:/data
  #   environment:
  #     - GF_PATHS_DATA=/data/grafana
  #   labels:
  #     - traefik.enable=true
  #     - "traefik.http.routers.lgtm.rule=Host(`grafana.tangram-orchestre.fr`)"
  #     - traefik.http.services.lgtm.loadbalancer.server.port=3000
  #     - traefik.http.routers.lgtm.tls=true
  #     - traefik.http.routers.lgtm.tls.certresolver=resolver
  #     - traefik.http.routers.lgtm.middlewares=authentik@file

  grafana:
    image: grafana/grafana-oss:11.3.4
    restart: unless-stopped
    profiles:
      - observability
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - /opt/docker-volumes/grafana:/var/lib/grafana
    user: root:root
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.tangram-orchestre.fr
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
    labels:
      - traefik.enable=true
      - "traefik.http.routers.lgtm.rule=Host(`grafana.tangram-orchestre.fr`)"
      - traefik.http.services.lgtm.loadbalancer.server.port=3000
      - traefik.http.routers.lgtm.tls=true
      - traefik.http.routers.lgtm.tls.certresolver=resolver

  # Collector
  alloy:
    image: grafana/alloy:v1.6.1
    restart: unless-stopped
    profiles:
      - observability
    depends_on:
      - loki
      - prometheus
      - node-exporter
      - cadvisor
    security_opt:
      - no-new-privileges:true
    volumes:
      - /run/user/${UID}/docker.sock:/var/run/docker.sock:ro
      - ./config.alloy:/etc/alloy/config.alloy
      - /opt/docker-volumes-no-backup/alloy:/var/lib/alloy/data
    command: "run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy"
    extra_hosts:
      - host.docker.internal=host-gateway
    labels:
      - traefik.enable=true
      - "traefik.http.routers.alloy.rule=Host(`alloy.tangram-orchestre.fr`)"
      - traefik.http.services.alloy.loadbalancer.server.port=12345
      - traefik.http.routers.alloy.tls=true
      - traefik.http.routers.alloy.tls.certresolver=resolver
      - traefik.http.routers.alloy.middlewares=authentik@file

  loki:
    image: grafana/loki:3.4.1
    restart: unless-stopped
    profiles:
      - observability
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - /opt/docker-volumes-no-backup/loki:/tmp/loki/
    command: "-config.file=/etc/loki/local-config.yaml"

  prometheus:
    image: prom/prometheus:v3.2.1
    restart: unless-stopped
    profiles:
      - observability
    security_opt:
      - no-new-privileges:true
    user: root:root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/docker-volumes-no-backup/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=2w"
      - "--storage.tsdb.retention.size=2GB"

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.9.0
    restart: unless-stopped
    profiles:
      - observability
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.disable-defaults"
      - "--collector.cpu"
      - "--collector.cpufreq"
      - "--collector.loadavg"
      - "--collector.pressure"
      - "--collector.netdev"
      - "--collector.diskstats"
      - "--collector.filesystem"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.meminfo"
      - "--collector.ethtool"
      - "--collector.ethtool.device-include=^ens3$$"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.2
    restart: unless-stopped
    profiles:
      - observability
    volumes:
      - /:/rootfs:ro
      - /run/user/${UID}/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - ~/.local/share/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
