name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: contains(fromJSON('["dependabot[bot]", "lvaroqui"]'), github.actor)
    steps:
      - uses: hmarr/auto-approve-action@v4
