name: Create Merge back master to develop pull request
on:
  push:
    branches:
      - master

jobs:
  create-pr-merge-back-master-to-develop:
    name: Create Merge back master to develop pull request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop
      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          ref: master
          base: develop
          filters: |
            any:
              - '**'
      - name: Reset master branch
        if: steps.changes.outputs.any == 'true'
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        if: steps.changes.outputs.any == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: merge-back-master
          draft: always-true
          title: Merge back master to develop
