name: CI/CD
on:
  push:
    branches:
      - master

# Ensure deployments are sequential
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build-showcase-website:
    name: Build Showcase Website
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: ./.github/workflows/build-showcase-website.yml
    with:
      base_ref: production
      push: true
    secrets: inherit

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-showcase-website

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync production dir to production
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude='.env'
          path: production/
          remote_path: /opt/services/
          remote_host: tangram-orchestre.fr
          remote_user: ${{ secrets.PRODUCTION_USERNAME }}
          remote_key: ${{ secrets.PRODUCTION_KEY }}

      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: tangram-orchestre.fr
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }}
          script: /opt/services/update.sh

      - name: Update production branch
        run: |
          git push --force origin HEAD:production
